services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    ports:
      - 37001:5432
    networks:
      - db
# Database web management
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - 37002:5050
    networks:
      - db

  server:
    container_name: server
    image: postgrest/postgrest
    ports:
      - "37000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/northwind
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:37000
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: web_anon
    networks:
      - db
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "37003:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:37000/
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local